Repository parkingkim/parking-BE, pull requests merged in 2024-03, with the labels that each got.

#33 Feat/#19 리뷰 관리 기능 구현
  src/main/java/com/example/parking/api/member/MemberController.java
  src/main/java/com/example/parking/api/review/ReviewController.java
  src/main/java/com/example/parking/api/searchcondition/SearchConditionController.java
  src/main/java/com/example/parking/application/review/ReviewService.java
  src/main/java/com/example/parking/application/review/dto/ReviewCountResponse.java
  src/main/java/com/example/parking/application/review/dto/ReviewCreateRequest.java
  src/main/java/com/example/parking/application/review/dto/ReviewInfoResponse.java
  src/main/java/com/example/parking/config/ApiRestTemplateConfig.java
  src/main/java/com/example/parking/config/ParkingApiErrorHandler.java
  src/main/java/com/example/parking/config/RestTemplateConfig.java
  src/main/java/com/example/parking/config/WebMvcConfig.java
  src/main/java/com/example/parking/config/argumentresolver/AuthArgumentResolver.java
  src/main/java/com/example/parking/config/argumentresolver/MemberAuth.java
  src/main/java/com/example/parking/config/interceptor/AuthInterceptor.java
  src/main/java/com/example/parking/domain/member/MemberRepository.java
  src/main/java/com/example/parking/domain/parking/Parking.java
  src/main/java/com/example/parking/domain/review/Content.java
  src/main/java/com/example/parking/domain/review/Review.java
  src/main/java/com/example/parking/domain/review/ReviewRepository.java
  src/main/java/com/example/parking/domain/review/service/ReviewDomainService.java
  src/main/java/com/example/parking/domain/searchcondition/SearchCondition.java
  src/main/java/com/example/parking/infra/converter/ContentConverter.java
  src/main/java/com/example/parking/infra/converter/EnumListConverter.java
  src/main/java/com/example/parking/infra/converter/FeeTypeConverter.java
  src/main/java/com/example/parking/infra/converter/OperationTypeConverter.java
  src/main/java/com/example/parking/infra/converter/ParkingTypeConverter.java
  src/main/java/com/example/parking/infra/converter/PayTypeConverter.java
  src/main/java/com/example/parking/support/Association.java
  src/test/java/com/example/parking/application/review/ReviewServiceTest.java
  src/test/java/com/example/parking/auth/MemberSessionRepositoryTest.java
  src/test/java/com/example/parking/domain/review/ContentTest.java
  src/test/java/com/example/parking/domain/review/service/ReviewDomainServiceTest.java
  src/test/java/com/example/parking/domain/searchcondition/EnumListConverterTest.java
  src/test/java/com/example/parking/fake/BasicMemberRepository.java
  src/test/java/com/example/parking/fake/BasicParkingRepository.java
  src/test/java/com/example/parking/fake/BasicRepository.java
  src/test/java/com/example/parking/fake/BasicReviewRepository.java
  src/test/resources/static/images/dummy.txt
  src/test/resources/static/images/test-image.png
Labels: 📝feature

#32 인증 코드 메일 전송 및 검증 기능 구현
  .github/workflows/ci.yml
  build.gradle
  src/main/java/com/example/parking/auth/AuthService.java
  src/main/java/com/example/parking/auth/authcode/AuthCodeCategory.java
  src/main/java/com/example/parking/auth/authcode/AuthCodePlatform.java
  src/main/java/com/example/parking/auth/authcode/InValidAuthCodeException.java
  src/main/java/com/example/parking/auth/authcode/api/AuthCodeController.java
  src/main/java/com/example/parking/auth/authcode/application/AuthCodeEventListener.java
  src/main/java/com/example/parking/auth/authcode/application/AuthCodeValidator.java
  src/main/java/com/example/parking/auth/authcode/application/MailPlatformValidator.java
  src/main/java/com/example/parking/auth/authcode/application/PlatformValidator.java
  src/main/java/com/example/parking/auth/authcode/application/dto/AuthCodeCertificateRequest.java
  src/main/java/com/example/parking/auth/authcode/application/dto/AuthCodeRequest.java
  src/main/java/com/example/parking/auth/authcode/application/dto/AuthCodeResponse.java
  src/main/java/com/example/parking/auth/authcode/event/AuthCodeCreateEvent.java
  src/main/java/com/example/parking/auth/authcode/infrastructure/AuthCodeSender.java
  src/main/java/com/example/parking/auth/authcode/infrastructure/MailAuthCodeSender.java
  src/main/java/com/example/parking/auth/authcode/util/AuthCodeKeyConverter.java
  src/main/java/com/example/parking/auth/session/MemberSession.java
  src/main/java/com/example/parking/auth/session/MemberSessionRepository.java
  src/main/java/com/example/parking/config/WebMvcConfig.java
  src/main/java/com/example/parking/config/argumentresolver/AuthArgumentResolver.java
  src/main/java/com/example/parking/config/interceptor/AuthInterceptor.java
  src/main/java/com/example/parking/external/config/RedisConfig.java
  src/main/java/com/example/parking/util/authcode/AuthCodeGenerator.java
  src/main/java/com/example/parking/util/authcode/NumberAuthCodeGenerator.java
  src/main/resources/application.yml
  src/test/java/com/example/parking/auth/AuthServiceTest.java
  src/test/java/com/example/parking/auth/MemberSessionRepositoryTest.java
  src/test/java/com/example/parking/config/TestConfig.java
  src/test/java/com/example/parking/container/ContainerTest.java
  src/test/java/com/example/parking/container/MySQLDataCleaner.java
  src/test/java/com/example/parking/container/RedisDataCleaner.java
  src/test/resources/application.yml
Labels: 📝feature

#42 feat: swagger 적용
  build.gradle
  src/main/java/com/example/parking/api/favorite/FavoriteController.java
  src/main/java/com/example/parking/api/member/MemberController.java
  src/main/java/com/example/parking/api/review/ReviewController.java
  src/main/java/com/example/parking/api/searchcondition/SearchConditionController.java
  src/main/java/com/example/parking/config/SwaggerConfig.java
  src/main/java/com/example/parking/config/WebMvcConfig.java
  src/main/java/com/example/parking/config/interceptor/AuthInterceptor.java
Labels: 📝feature

#44 컨테이너로 동작할 수 있게 설정
  Dockerfile
  build.gradle
  src/main/java/com/example/parking/application/searchcondition/SearchConditionService.java
  src/main/java/com/example/parking/domain/searchcondition/SearchCondition.java
  src/main/java/com/example/parking/external/scheduler/ParkingUpdateScheduler.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/db/migration/mysql/V1.0.0__initial_schema.sql
  src/test/resources/application.yml
Labels: 📝feature

#45 Create deploy.yml
  .github/workflows/ deploy.yml
Labels: 📝feature

#46 Fix: cors 적용
  src/main/java/com/example/parking/config/WebMvcConfig.java
Labels: 🎅🏼deploy, 🚨hotfix

#47 CD 테스트
  src/main/java/com/example/parking/config/WebMvcConfig.java
Labels: 🎅🏼deploy

#48 CD 테스트좀 하겠습니다
  src/main/java/com/example/parking/config/WebMvcConfig.java
  src/test/resources/static/images/dummy.txt
  src/test/resources/static/images/test-image.png
Labels: 🎅🏼deploy

#49 Revert "CD 테스트좀 하겠습니다"
  src/main/java/com/example/parking/config/WebMvcConfig.java
  src/test/resources/static/images/dummy.txt
  src/test/resources/static/images/test-image.png
Labels: 🎅🏼deploy

#50 Revert "Revert "CD 테스트좀 하겠습니다""
  src/main/java/com/example/parking/config/WebMvcConfig.java
  src/test/resources/static/images/dummy.txt
  src/test/resources/static/images/test-image.png
Labels: 🎅🏼deploy

#51 "CD 테스트좀 하겠습니다
  src/main/java/com/example/parking/config/WebMvcConfig.java
  src/test/resources/static/images/dummy.txt
  src/test/resources/static/images/test-image.png
Labels: 🎅🏼deploy

#52 Revert ""CD 테스트좀 하겠습니다"
  src/main/java/com/example/parking/config/WebMvcConfig.java
  src/test/resources/static/images/dummy.txt
  src/test/resources/static/images/test-image.png
Labels: 🎅🏼deploy

#53 Allow Oriign 수정
  src/main/java/com/example/parking/config/WebMvcConfig.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: 🪲bugfix, 🎅🏼deploy
