Repository parkingkim/parking-BE, pull requests merged in 2024-06, with the labels that each got.

#83 feat: 인증코드 유효기간 변경
  app-api/src/main/java/com/parkingcomestrue/parking/application/auth/AuthService.java
  app-api/src/main/resources/application.yml
Labels: 📝feature

#87 쿼리 분석 및 성능개선
  app-api/src/main/java/com/parkingcomestrue/parking/api/favorite/FavoriteController.java
  app-api/src/main/java/com/parkingcomestrue/parking/api/member/MemberController.java
  app-api/src/main/java/com/parkingcomestrue/parking/api/parking/ParkingController.java
  app-api/src/main/java/com/parkingcomestrue/parking/api/review/ReviewController.java
  app-api/src/main/java/com/parkingcomestrue/parking/api/searchcondition/SearchConditionController.java
  app-api/src/main/java/com/parkingcomestrue/parking/application/auth/AuthService.java
  app-api/src/main/java/com/parkingcomestrue/parking/application/favorite/FavoriteService.java
  app-api/src/main/java/com/parkingcomestrue/parking/application/member/MemberService.java
  app-api/src/main/java/com/parkingcomestrue/parking/application/member/dto/MemberId.java
  app-api/src/main/java/com/parkingcomestrue/parking/application/parking/ParkingService.java
  app-api/src/main/java/com/parkingcomestrue/parking/application/review/ReviewService.java
  app-api/src/main/java/com/parkingcomestrue/parking/application/review/dto/ReviewCreateRequest.java
  app-api/src/main/java/com/parkingcomestrue/parking/application/searchcondition/SearchConditionService.java
  app-api/src/main/java/com/parkingcomestrue/parking/config/argumentresolver/AuthArgumentResolver.java
  app-api/src/main/java/com/parkingcomestrue/parking/config/interceptor/AuthInterceptor.java
  app-api/src/main/java/com/parkingcomestrue/parking/controlleradvice/GlobalExceptionHandler.java
  app-api/src/test/java/com/parkingcomestrue/parking/application/auth/AuthServiceTest.java
  app-api/src/test/java/com/parkingcomestrue/parking/application/member/MemberServiceTest.java
  app-api/src/test/java/com/parkingcomestrue/parking/application/parking/ParkingServiceTest.java
  app-api/src/test/java/com/parkingcomestrue/parking/application/review/ReviewServiceTest.java
  app-scheduler/src/test/java/com/parkingcomestrue/external/api/CircuitBreakerAspectTest.java
  app-scheduler/src/test/java/com/parkingcomestrue/fake/CircuitBreakerTestService.java
  domain/src/main/java/com/parkingcomestrue/common/domain/parking/TimeInfo.java
  domain/src/main/java/com/parkingcomestrue/common/domain/review/Review.java
  domain/src/main/java/com/parkingcomestrue/common/domain/searchcondition/SearchCondition.java
  domain/src/main/java/com/parkingcomestrue/common/domain/searchcondition/repository/SearchConditionRepository.java
  domain/src/main/resources/db/migration/mysql/V5.0.1__add_index.sql
  domain/src/testFixtures/java/repository/FakeSearchConditionRepository.java
Labels: 🪓refactor, 🎅🏼deploy

#88 Fix/HttpServletRequest null일때 예외처리
  app-api/src/main/java/com/parkingcomestrue/parking/config/argumentresolver/AuthArgumentResolver.java
Labels: 🪲bugfix, 🎅🏼deploy

#89 fix: cookie null 일때, 예외처리
  app-api/src/main/java/com/parkingcomestrue/parking/config/argumentresolver/AuthArgumentResolver.java
Labels: 🪲bugfix, 🎅🏼deploy
