Repository parkingkim/parking-BE, pull requests merged in 2024-04, with the labels that each got.

#57 Fix: flway v2 추가
  src/main/resources/db/migration/mysql/V2.0.0__add_point_parking_table.sql
Labels: 🎅🏼deploy, 🚨hotfix

#58 Hotfix/ 주차장 반경 조회 null exception 수정
  src/main/java/com/example/parking/auth/authcode/api/AuthCodeController.java
  src/main/java/com/example/parking/config/SwaggerConfig.java
  src/main/java/com/example/parking/config/argumentresolver/parking/ParkingSearchConditionArgumentResolver.java
Labels: 🎅🏼deploy, 🚨hotfix

#60 주차장 반경 조회 문제 해결
  src/main/java/com/example/parking/ParkingApplication.java
  src/main/java/com/example/parking/application/parking/ParkingService.java
  src/main/java/com/example/parking/application/parking/dto/ParkingQueryRequest.java
  src/main/java/com/example/parking/config/argumentresolver/parking/ParkingQueryArgumentResolver.java
  src/main/java/com/example/parking/domain/parking/Location.java
  src/main/java/com/example/parking/domain/parking/PayTypes.java
  src/main/java/com/example/parking/domain/parking/TimeUnit.java
  src/main/java/com/example/parking/external/coordinate/dto/CoordinateResponse.java
  src/main/java/com/example/parking/support/exception/ExceptionInformation.java
  src/main/resources/db/migration/mysql/V3.0.0__drop_column_parking_table.sql
  src/test/java/com/example/parking/domain/parking/BaseInformationTest.java
Labels: 🎅🏼deploy, 🚨hotfix

#56 주차장 상세조회
  src/main/java/com/example/parking/api/parking/ParkingController.java
  src/main/java/com/example/parking/application/parking/ParkingService.java
  src/main/java/com/example/parking/application/parking/dto/ParkingDetailInfoResponse.java
  src/main/java/com/example/parking/domain/parking/FeePolicy.java
  src/main/java/com/example/parking/domain/parking/OperatingTime.java
  src/main/java/com/example/parking/domain/parking/Parking.java
  src/main/java/com/example/parking/domain/parking/Space.java
  src/main/java/com/example/parking/domain/parking/TimeInfo.java
  src/main/java/com/example/parking/domain/parking/repository/ParkingRepository.java
  src/test/java/com/example/parking/application/parking/ParkingServiceTest.java
  src/test/java/com/example/parking/auth/AuthServiceTest.java
  src/test/java/com/example/parking/container/ContainerTest.java
  src/test/java/com/example/parking/external/scheduler/ParkingUpdateSchedulerTest.java
  src/test/java/com/example/parking/fake/FakeParkingService.java
  src/test/java/com/example/parking/fake/FakeReviewService.java
Labels: 📝feature, 🎅🏼deploy

#61 테스트 위도경도 범위 수정
  src/test/java/com/example/parking/application/parking/ParkingServiceTest.java
Labels: 🪲bugfix

#63 회원 실명 삭제
  src/main/java/com/example/parking/application/member/MemberService.java
  src/main/java/com/example/parking/domain/member/Member.java
  src/main/resources/db/migration/mysql/V4.0.0__drop_column_member_table.sql
  src/test/java/com/example/parking/application/parking/ParkingServiceTest.java
  src/test/java/com/example/parking/domain/member/MemberTest.java
  src/test/java/com/example/parking/fake/BasicMemberRepository.java
Labels: 🪓refactor, 🎅🏼deploy

#72 FIx: CD 스크립트 수정
  .github/workflows/ deploy.yml
Labels: 🪲bugfix, 🎅🏼deploy

#75 모니터링 추가
  app-api/build.gradle
  app-api/src/main/java/com/parkingcomestrue/parking/config/WebMvcConfig.java
  app-api/src/main/resources/application-prod.yml
  app-scheduler/build.gradle
  app-scheduler/src/main/resources/application-prod.yml
Labels: 📝feature, 🎅🏼deploy

#76 배포 테스트
  app-api/src/test/resources/static/deploy.txt
  app-scheduler/src/test/resources/static/deploy.txt
Labels: 🪲bugfix, 🎅🏼deploy

#77 배포 테스트
  .github/workflows/ deploy.yml
  app-api/src/test/resources/static/deploy.txt
  app-scheduler/src/test/resources/static/deploy.txt
Labels: 🪲bugfix, 🎅🏼deploy
